package org.shakvilla.beatzmedia.audit.domain;

import java.time.Instant;

/**
 * Immutable audit-trail record. Append-only: once created it is never mutated. Pure Java, no
 * framework imports. INV-10 / audit ADD §domain.
 *
 * <p>Fields:
 *
 * <ul>
 *   <li>{@code id} — opaque UUIDv7 string (generated by the use-case service via
 *       {@link org.shakvilla.beatzmedia.platform.application.port.out.IdGenerator}).
 *   <li>{@code actor} — account-id string of the principal performing the action.
 *   <li>{@code actorName} — display name of the actor (nullable; populated from JWT or account
 *       lookup at write time). Used by the read endpoint so no cross-module join is needed.
 *   <li>{@code action} — human-readable action label, e.g. {@code "Invited admin"}.
 *   <li>{@code targetType} — class/entity name of the target, e.g. {@code "AdminMember"}.
 *   <li>{@code targetId} — id of the target resource.
 *   <li>{@code type} — high-level category ({@link AuditType}).
 *   <li>{@code reason} — nullable free-text reason supplied by the actor.
 *   <li>{@code occurredAt} — wall-clock instant (UTC) from
 *       {@link org.shakvilla.beatzmedia.platform.application.port.out.Clock}.
 * </ul>
 */
public final class AuditEntry {

  private final String id;
  private final String actor;
  private final String actorName;
  private final String action;
  private final String targetType;
  private final String targetId;
  private final AuditType type;
  private final String reason;
  private final Instant occurredAt;

  /**
   * Full constructor including actorName. Used by WU-AUD-1 read projection and new audited
   * services.
   */
  public AuditEntry(
      String id,
      String actor,
      String actorName,
      String action,
      String targetType,
      String targetId,
      AuditType type,
      String reason,
      Instant occurredAt) {
    this.id = id;
    this.actor = actor;
    this.actorName = actorName;
    this.action = action;
    this.targetType = targetType;
    this.targetId = targetId;
    this.type = type;
    this.reason = reason;
    this.occurredAt = occurredAt;
  }

  /**
   * Legacy constructor for callers that do not supply an actor display name. {@code actorName}
   * defaults to {@code null}. Retained for backward compatibility with WU-IDN-4 services that
   * already call {@link org.shakvilla.beatzmedia.audit.application.port.out.AuditWriter#append}
   * directly without a display name.
   */
  public AuditEntry(
      String id,
      String actor,
      String action,
      String targetType,
      String targetId,
      AuditType type,
      String reason,
      Instant occurredAt) {
    this(id, actor, null, action, targetType, targetId, type, reason, occurredAt);
  }

  public String getId() {
    return id;
  }

  public String getActor() {
    return actor;
  }

  public String getActorName() {
    return actorName;
  }

  public String getAction() {
    return action;
  }

  public String getTargetType() {
    return targetType;
  }

  public String getTargetId() {
    return targetId;
  }

  public AuditType getType() {
    return type;
  }

  public String getReason() {
    return reason;
  }

  public Instant getOccurredAt() {
    return occurredAt;
  }
}
