-- V801__create_search_document.sql
-- Search index lifecycle (WU-SRCH-1): search_document table + indexes.
-- Band: V8xx (search/store). Constraint: INV-SRCH-1 unique (entity_type,entity_id).

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE search_document (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT        NOT NULL,
    entity_id   TEXT        NOT NULL,
    title       TEXT        NOT NULL,
    subtitle    TEXT,
    search_text TEXT        NOT NULL DEFAULT '',
    tsv         TSVECTOR    NOT NULL DEFAULT ''::tsvector,
    popularity  BIGINT      NOT NULL DEFAULT 0,
    visible     BOOLEAN     NOT NULL DEFAULT TRUE,
    payload     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    indexed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_search_document_entity UNIQUE (entity_type, entity_id),
    CONSTRAINT ck_search_document_type CHECK (entity_type IN
        ('TRACK','ARTIST','ALBUM','PLAYLIST','STORE_ITEM','PODCAST','EVENT'))
);

-- Full-text relevance index (INV-SRCH-4).
CREATE INDEX idx_search_document_tsv ON search_document USING GIN (tsv);
-- Typo-tolerant / prefix similarity (pg_trgm), OQ-12 default backend.
CREATE INDEX idx_search_document_title_trgm ON search_document USING GIN (title gin_trgm_ops);
-- Filter support: entity_type + visible (INV-SRCH-2).
CREATE INDEX idx_search_document_type_visible ON search_document (entity_type, visible);
-- Sort support: popularity DESC (store browse, popular sort).
CREATE INDEX idx_search_document_popularity ON search_document (popularity DESC);
