-- V943__commerce_cart.sql
-- Commerce module (WU-COM-1): per-account cart + cart lines. Commerce ADD §7.
-- Band: V9xx (post-audit additions land in the next free global slot per
-- scripts/next-migration-version.sh). Money in integer minor units (pesewas), INV-11.

-- Ids are TEXT (UUIDv7 strings generated by the platform IdGenerator), matching the
-- codebase-wide convention for entity primary keys (e.g. track.id, album.id) rather than the
-- native Postgres UUID type.
CREATE TABLE cart (
    id          TEXT        PRIMARY KEY,
    account_id  VARCHAR(64) NOT NULL,
    CONSTRAINT uq_cart_account UNIQUE (account_id)
);

CREATE TABLE cart_item (
    id               TEXT        PRIMARY KEY,
    cart_id          TEXT        NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
    line_id          VARCHAR(160) NOT NULL,
    kind             VARCHAR(16) NOT NULL,
    ref_id           VARCHAR(64) NOT NULL,
    title            VARCHAR(256) NOT NULL,
    subtitle         VARCHAR(256),
    image            VARCHAR(512),
    unit_price_minor BIGINT NOT NULL,
    currency         VARCHAR(8) NOT NULL DEFAULT 'GHS',
    qty              INT NOT NULL DEFAULT 1,
    stackable        BOOLEAN NOT NULL DEFAULT FALSE,
    metadata         JSONB,
    CONSTRAINT ck_cart_item_kind CHECK (kind IN
        ('track', 'album', 'album-rest', 'store', 'episode', 'season-pass', 'ticket')),
    CONSTRAINT ck_cart_item_qty_range CHECK (qty BETWEEN 1 AND 99),
    CONSTRAINT ck_cart_item_price_non_negative CHECK (unit_price_minor >= 0),
    -- Collapses duplicate non-stackable adds; also the natural lookup key for updates/removals.
    CONSTRAINT uq_cart_item_cart_line UNIQUE (cart_id, line_id)
);

-- Primary access pattern: load all lines for a cart (GET /v1/me/cart, add/update/remove).
CREATE INDEX ix_cart_item_cart ON cart_item (cart_id);
