/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackTrackIdRouteImport } from './routes/track.$trackId'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioReleasesRouteImport } from './routes/studio.releases'
import { Route as StudioProfileRouteImport } from './routes/studio.profile'
import { Route as StudioPodcastsRouteImport } from './routes/studio.podcasts'
import { Route as StudioPayoutsRouteImport } from './routes/studio.payouts'
import { Route as StudioAudienceRouteImport } from './routes/studio.audience'
import { Route as StudioAnalyticsRouteImport } from './routes/studio.analytics'
import { Route as StoreMerchRouteImport } from './routes/store.merch'
import { Route as StoreHifiRouteImport } from './routes/store.hifi'
import { Route as StoreExclusivesRouteImport } from './routes/store.exclusives'
import { Route as StoreBeatsRouteImport } from './routes/store.beats'
import { Route as StoreItemIdRouteImport } from './routes/store.$itemId'
import { Route as PodcastPodcastIdRouteImport } from './routes/podcast.$podcastId'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as CheckoutCompleteRouteImport } from './routes/checkout.complete'
import { Route as ArtistArtistIdRouteImport } from './routes/artist/$artistId'
import { Route as AlbumAlbumIdRouteImport } from './routes/album/$albumId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrustRouteImport } from './routes/admin.trust'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEditorialRouteImport } from './routes/admin.editorial'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as StudioPodcastsIndexRouteImport } from './routes/studio.podcasts.index'
import { Route as AdminFinanceIndexRouteImport } from './routes/admin.finance.index'
import { Route as StudioReleaseNewRouteImport } from './routes/studio.release.new'
import { Route as StudioReleaseReleaseIdRouteImport } from './routes/studio.release.$releaseId'
import { Route as StudioPodcastsNewRouteImport } from './routes/studio.podcasts.new'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminFinanceLedgerRouteImport } from './routes/admin.finance.ledger'
import { Route as AdminCatalogItemIdRouteImport } from './routes/admin.catalog.$itemId'
import { Route as StudioReleaseNewIndexRouteImport } from './routes/studio.release.new.index'
import { Route as StudioReleaseNewTracksRouteImport } from './routes/studio.release.new.tracks'
import { Route as StudioReleaseNewSplitsRouteImport } from './routes/studio.release.new.splits'
import { Route as StudioReleaseNewReviewRouteImport } from './routes/studio.release.new.review'
import { Route as StudioReleaseNewDetailsRouteImport } from './routes/studio.release.new.details'
import { Route as AdminFinanceDisputeDisputeIdRouteImport } from './routes/admin.finance.dispute.$disputeId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReleasesRoute = StudioReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => StudioRoute,
} as any)
const StudioProfileRoute = StudioProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPodcastsRoute = StudioPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPayoutsRoute = StudioPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAudienceRoute = StudioAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAnalyticsRoute = StudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudioRoute,
} as any)
const StoreMerchRoute = StoreMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => StoreRoute,
} as any)
const StoreHifiRoute = StoreHifiRouteImport.update({
  id: '/hifi',
  path: '/hifi',
  getParentRoute: () => StoreRoute,
} as any)
const StoreExclusivesRoute = StoreExclusivesRouteImport.update({
  id: '/exclusives',
  path: '/exclusives',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBeatsRoute = StoreBeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => StoreRoute,
} as any)
const StoreItemIdRoute = StoreItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => StoreRoute,
} as any)
const PodcastPodcastIdRoute = PodcastPodcastIdRouteImport.update({
  id: '/podcast/$podcastId',
  path: '/podcast/$podcastId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCompleteRoute = CheckoutCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => CheckoutRoute,
} as any)
const ArtistArtistIdRoute = ArtistArtistIdRouteImport.update({
  id: '/artist/$artistId',
  path: '/artist/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrustRoute = AdminTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialRoute = AdminEditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const StudioPodcastsIndexRoute = StudioPodcastsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioPodcastsRoute,
} as any)
const AdminFinanceIndexRoute = AdminFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const StudioReleaseNewRoute = StudioReleaseNewRouteImport.update({
  id: '/release/new',
  path: '/release/new',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReleaseReleaseIdRoute = StudioReleaseReleaseIdRouteImport.update({
  id: '/release/$releaseId',
  path: '/release/$releaseId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPodcastsNewRoute = StudioPodcastsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioPodcastsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminFinanceLedgerRoute = AdminFinanceLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminFinanceRoute,
} as any)
const AdminCatalogItemIdRoute = AdminCatalogItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const StudioReleaseNewIndexRoute = StudioReleaseNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioReleaseNewRoute,
} as any)
const StudioReleaseNewTracksRoute = StudioReleaseNewTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => StudioReleaseNewRoute,
} as any)
const StudioReleaseNewSplitsRoute = StudioReleaseNewSplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => StudioReleaseNewRoute,
} as any)
const StudioReleaseNewReviewRoute = StudioReleaseNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => StudioReleaseNewRoute,
} as any)
const StudioReleaseNewDetailsRoute = StudioReleaseNewDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => StudioReleaseNewRoute,
} as any)
const AdminFinanceDisputeDisputeIdRoute =
  AdminFinanceDisputeDisputeIdRouteImport.update({
    id: '/dispute/$disputeId',
    path: '/dispute/$disputeId',
    getParentRoute: () => AdminFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/notifications': typeof NotificationsRoute
  '/podcasts': typeof PodcastsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/podcast/$podcastId': typeof PodcastPodcastIdRoute
  '/store/$itemId': typeof StoreItemIdRoute
  '/store/beats': typeof StoreBeatsRoute
  '/store/exclusives': typeof StoreExclusivesRoute
  '/store/hifi': typeof StoreHifiRoute
  '/store/merch': typeof StoreMerchRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/payouts': typeof StudioPayoutsRoute
  '/studio/podcasts': typeof StudioPodcastsRouteWithChildren
  '/studio/profile': typeof StudioProfileRoute
  '/studio/releases': typeof StudioReleasesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/store/': typeof StoreIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/catalog/$itemId': typeof AdminCatalogItemIdRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/studio/podcasts/new': typeof StudioPodcastsNewRoute
  '/studio/release/$releaseId': typeof StudioReleaseReleaseIdRoute
  '/studio/release/new': typeof StudioReleaseNewRouteWithChildren
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/studio/podcasts/': typeof StudioPodcastsIndexRoute
  '/admin/finance/dispute/$disputeId': typeof AdminFinanceDisputeDisputeIdRoute
  '/studio/release/new/details': typeof StudioReleaseNewDetailsRoute
  '/studio/release/new/review': typeof StudioReleaseNewReviewRoute
  '/studio/release/new/splits': typeof StudioReleaseNewSplitsRoute
  '/studio/release/new/tracks': typeof StudioReleaseNewTracksRoute
  '/studio/release/new/': typeof StudioReleaseNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/notifications': typeof NotificationsRoute
  '/podcasts': typeof PodcastsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/podcast/$podcastId': typeof PodcastPodcastIdRoute
  '/store/$itemId': typeof StoreItemIdRoute
  '/store/beats': typeof StoreBeatsRoute
  '/store/exclusives': typeof StoreExclusivesRoute
  '/store/hifi': typeof StoreHifiRoute
  '/store/merch': typeof StoreMerchRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/payouts': typeof StudioPayoutsRoute
  '/studio/profile': typeof StudioProfileRoute
  '/studio/releases': typeof StudioReleasesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/store': typeof StoreIndexRoute
  '/studio': typeof StudioIndexRoute
  '/admin/catalog/$itemId': typeof AdminCatalogItemIdRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/studio/podcasts/new': typeof StudioPodcastsNewRoute
  '/studio/release/$releaseId': typeof StudioReleaseReleaseIdRoute
  '/admin/finance': typeof AdminFinanceIndexRoute
  '/studio/podcasts': typeof StudioPodcastsIndexRoute
  '/admin/finance/dispute/$disputeId': typeof AdminFinanceDisputeDisputeIdRoute
  '/studio/release/new/details': typeof StudioReleaseNewDetailsRoute
  '/studio/release/new/review': typeof StudioReleaseNewReviewRoute
  '/studio/release/new/splits': typeof StudioReleaseNewSplitsRoute
  '/studio/release/new/tracks': typeof StudioReleaseNewTracksRoute
  '/studio/release/new': typeof StudioReleaseNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/events': typeof EventsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/notifications': typeof NotificationsRoute
  '/podcasts': typeof PodcastsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/store': typeof StoreRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/editorial': typeof AdminEditorialRoute
  '/admin/finance': typeof AdminFinanceRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trust': typeof AdminTrustRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/artist/$artistId': typeof ArtistArtistIdRoute
  '/checkout/complete': typeof CheckoutCompleteRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
  '/podcast/$podcastId': typeof PodcastPodcastIdRoute
  '/store/$itemId': typeof StoreItemIdRoute
  '/store/beats': typeof StoreBeatsRoute
  '/store/exclusives': typeof StoreExclusivesRoute
  '/store/hifi': typeof StoreHifiRoute
  '/store/merch': typeof StoreMerchRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/payouts': typeof StudioPayoutsRoute
  '/studio/podcasts': typeof StudioPodcastsRouteWithChildren
  '/studio/profile': typeof StudioProfileRoute
  '/studio/releases': typeof StudioReleasesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/store/': typeof StoreIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/catalog/$itemId': typeof AdminCatalogItemIdRoute
  '/admin/finance/ledger': typeof AdminFinanceLedgerRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/studio/podcasts/new': typeof StudioPodcastsNewRoute
  '/studio/release/$releaseId': typeof StudioReleaseReleaseIdRoute
  '/studio/release/new': typeof StudioReleaseNewRouteWithChildren
  '/admin/finance/': typeof AdminFinanceIndexRoute
  '/studio/podcasts/': typeof StudioPodcastsIndexRoute
  '/admin/finance/dispute/$disputeId': typeof AdminFinanceDisputeDisputeIdRoute
  '/studio/release/new/details': typeof StudioReleaseNewDetailsRoute
  '/studio/release/new/review': typeof StudioReleaseNewReviewRoute
  '/studio/release/new/splits': typeof StudioReleaseNewSplitsRoute
  '/studio/release/new/tracks': typeof StudioReleaseNewTracksRoute
  '/studio/release/new/': typeof StudioReleaseNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/events'
    | '/library'
    | '/login'
    | '/lyrics'
    | '/notifications'
    | '/podcasts'
    | '/search'
    | '/settings'
    | '/signup'
    | '/store'
    | '/studio'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/compliance'
    | '/admin/editorial'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trust'
    | '/admin/users'
    | '/album/$albumId'
    | '/artist/$artistId'
    | '/checkout/complete'
    | '/event/$eventId'
    | '/playlist/$playlistId'
    | '/podcast/$podcastId'
    | '/store/$itemId'
    | '/store/beats'
    | '/store/exclusives'
    | '/store/hifi'
    | '/store/merch'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/payouts'
    | '/studio/podcasts'
    | '/studio/profile'
    | '/studio/releases'
    | '/studio/settings'
    | '/track/$trackId'
    | '/admin/'
    | '/checkout/'
    | '/store/'
    | '/studio/'
    | '/admin/catalog/$itemId'
    | '/admin/finance/ledger'
    | '/admin/users/$userId'
    | '/studio/podcasts/new'
    | '/studio/release/$releaseId'
    | '/studio/release/new'
    | '/admin/finance/'
    | '/studio/podcasts/'
    | '/admin/finance/dispute/$disputeId'
    | '/studio/release/new/details'
    | '/studio/release/new/review'
    | '/studio/release/new/splits'
    | '/studio/release/new/tracks'
    | '/studio/release/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/events'
    | '/library'
    | '/login'
    | '/lyrics'
    | '/notifications'
    | '/podcasts'
    | '/search'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/compliance'
    | '/admin/editorial'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trust'
    | '/admin/users'
    | '/album/$albumId'
    | '/artist/$artistId'
    | '/checkout/complete'
    | '/event/$eventId'
    | '/playlist/$playlistId'
    | '/podcast/$podcastId'
    | '/store/$itemId'
    | '/store/beats'
    | '/store/exclusives'
    | '/store/hifi'
    | '/store/merch'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/payouts'
    | '/studio/profile'
    | '/studio/releases'
    | '/studio/settings'
    | '/track/$trackId'
    | '/admin'
    | '/checkout'
    | '/store'
    | '/studio'
    | '/admin/catalog/$itemId'
    | '/admin/finance/ledger'
    | '/admin/users/$userId'
    | '/studio/podcasts/new'
    | '/studio/release/$releaseId'
    | '/admin/finance'
    | '/studio/podcasts'
    | '/admin/finance/dispute/$disputeId'
    | '/studio/release/new/details'
    | '/studio/release/new/review'
    | '/studio/release/new/splits'
    | '/studio/release/new/tracks'
    | '/studio/release/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/events'
    | '/library'
    | '/login'
    | '/lyrics'
    | '/notifications'
    | '/podcasts'
    | '/search'
    | '/settings'
    | '/signup'
    | '/store'
    | '/studio'
    | '/admin/audit'
    | '/admin/catalog'
    | '/admin/compliance'
    | '/admin/editorial'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/trust'
    | '/admin/users'
    | '/album/$albumId'
    | '/artist/$artistId'
    | '/checkout/complete'
    | '/event/$eventId'
    | '/playlist/$playlistId'
    | '/podcast/$podcastId'
    | '/store/$itemId'
    | '/store/beats'
    | '/store/exclusives'
    | '/store/hifi'
    | '/store/merch'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/payouts'
    | '/studio/podcasts'
    | '/studio/profile'
    | '/studio/releases'
    | '/studio/settings'
    | '/track/$trackId'
    | '/admin/'
    | '/checkout/'
    | '/store/'
    | '/studio/'
    | '/admin/catalog/$itemId'
    | '/admin/finance/ledger'
    | '/admin/users/$userId'
    | '/studio/podcasts/new'
    | '/studio/release/$releaseId'
    | '/studio/release/new'
    | '/admin/finance/'
    | '/studio/podcasts/'
    | '/admin/finance/dispute/$disputeId'
    | '/studio/release/new/details'
    | '/studio/release/new/review'
    | '/studio/release/new/splits'
    | '/studio/release/new/tracks'
    | '/studio/release/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  EventsRoute: typeof EventsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LyricsRoute: typeof LyricsRoute
  NotificationsRoute: typeof NotificationsRoute
  PodcastsRoute: typeof PodcastsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StoreRoute: typeof StoreRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  ArtistArtistIdRoute: typeof ArtistArtistIdRoute
  EventEventIdRoute: typeof EventEventIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
  PodcastPodcastIdRoute: typeof PodcastPodcastIdRoute
  TrackTrackIdRoute: typeof TrackTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/releases': {
      id: '/studio/releases'
      path: '/releases'
      fullPath: '/studio/releases'
      preLoaderRoute: typeof StudioReleasesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/profile': {
      id: '/studio/profile'
      path: '/profile'
      fullPath: '/studio/profile'
      preLoaderRoute: typeof StudioProfileRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/podcasts': {
      id: '/studio/podcasts'
      path: '/podcasts'
      fullPath: '/studio/podcasts'
      preLoaderRoute: typeof StudioPodcastsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/payouts': {
      id: '/studio/payouts'
      path: '/payouts'
      fullPath: '/studio/payouts'
      preLoaderRoute: typeof StudioPayoutsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/audience': {
      id: '/studio/audience'
      path: '/audience'
      fullPath: '/studio/audience'
      preLoaderRoute: typeof StudioAudienceRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/analytics': {
      id: '/studio/analytics'
      path: '/analytics'
      fullPath: '/studio/analytics'
      preLoaderRoute: typeof StudioAnalyticsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/store/merch': {
      id: '/store/merch'
      path: '/merch'
      fullPath: '/store/merch'
      preLoaderRoute: typeof StoreMerchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/hifi': {
      id: '/store/hifi'
      path: '/hifi'
      fullPath: '/store/hifi'
      preLoaderRoute: typeof StoreHifiRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/exclusives': {
      id: '/store/exclusives'
      path: '/exclusives'
      fullPath: '/store/exclusives'
      preLoaderRoute: typeof StoreExclusivesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/beats': {
      id: '/store/beats'
      path: '/beats'
      fullPath: '/store/beats'
      preLoaderRoute: typeof StoreBeatsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$itemId': {
      id: '/store/$itemId'
      path: '/$itemId'
      fullPath: '/store/$itemId'
      preLoaderRoute: typeof StoreItemIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/podcast/$podcastId': {
      id: '/podcast/$podcastId'
      path: '/podcast/$podcastId'
      fullPath: '/podcast/$podcastId'
      preLoaderRoute: typeof PodcastPodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/complete': {
      id: '/checkout/complete'
      path: '/complete'
      fullPath: '/checkout/complete'
      preLoaderRoute: typeof CheckoutCompleteRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/artist/$artistId': {
      id: '/artist/$artistId'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trust': {
      id: '/admin/trust'
      path: '/trust'
      fullPath: '/admin/trust'
      preLoaderRoute: typeof AdminTrustRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editorial': {
      id: '/admin/editorial'
      path: '/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AdminEditorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/studio/podcasts/': {
      id: '/studio/podcasts/'
      path: '/'
      fullPath: '/studio/podcasts/'
      preLoaderRoute: typeof StudioPodcastsIndexRouteImport
      parentRoute: typeof StudioPodcastsRoute
    }
    '/admin/finance/': {
      id: '/admin/finance/'
      path: '/'
      fullPath: '/admin/finance/'
      preLoaderRoute: typeof AdminFinanceIndexRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/studio/release/new': {
      id: '/studio/release/new'
      path: '/release/new'
      fullPath: '/studio/release/new'
      preLoaderRoute: typeof StudioReleaseNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/release/$releaseId': {
      id: '/studio/release/$releaseId'
      path: '/release/$releaseId'
      fullPath: '/studio/release/$releaseId'
      preLoaderRoute: typeof StudioReleaseReleaseIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/podcasts/new': {
      id: '/studio/podcasts/new'
      path: '/new'
      fullPath: '/studio/podcasts/new'
      preLoaderRoute: typeof StudioPodcastsNewRouteImport
      parentRoute: typeof StudioPodcastsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/finance/ledger': {
      id: '/admin/finance/ledger'
      path: '/ledger'
      fullPath: '/admin/finance/ledger'
      preLoaderRoute: typeof AdminFinanceLedgerRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
    '/admin/catalog/$itemId': {
      id: '/admin/catalog/$itemId'
      path: '/$itemId'
      fullPath: '/admin/catalog/$itemId'
      preLoaderRoute: typeof AdminCatalogItemIdRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/studio/release/new/': {
      id: '/studio/release/new/'
      path: '/'
      fullPath: '/studio/release/new/'
      preLoaderRoute: typeof StudioReleaseNewIndexRouteImport
      parentRoute: typeof StudioReleaseNewRoute
    }
    '/studio/release/new/tracks': {
      id: '/studio/release/new/tracks'
      path: '/tracks'
      fullPath: '/studio/release/new/tracks'
      preLoaderRoute: typeof StudioReleaseNewTracksRouteImport
      parentRoute: typeof StudioReleaseNewRoute
    }
    '/studio/release/new/splits': {
      id: '/studio/release/new/splits'
      path: '/splits'
      fullPath: '/studio/release/new/splits'
      preLoaderRoute: typeof StudioReleaseNewSplitsRouteImport
      parentRoute: typeof StudioReleaseNewRoute
    }
    '/studio/release/new/review': {
      id: '/studio/release/new/review'
      path: '/review'
      fullPath: '/studio/release/new/review'
      preLoaderRoute: typeof StudioReleaseNewReviewRouteImport
      parentRoute: typeof StudioReleaseNewRoute
    }
    '/studio/release/new/details': {
      id: '/studio/release/new/details'
      path: '/details'
      fullPath: '/studio/release/new/details'
      preLoaderRoute: typeof StudioReleaseNewDetailsRouteImport
      parentRoute: typeof StudioReleaseNewRoute
    }
    '/admin/finance/dispute/$disputeId': {
      id: '/admin/finance/dispute/$disputeId'
      path: '/dispute/$disputeId'
      fullPath: '/admin/finance/dispute/$disputeId'
      preLoaderRoute: typeof AdminFinanceDisputeDisputeIdRouteImport
      parentRoute: typeof AdminFinanceRoute
    }
  }
}

interface AdminCatalogRouteChildren {
  AdminCatalogItemIdRoute: typeof AdminCatalogItemIdRoute
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogItemIdRoute: AdminCatalogItemIdRoute,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminFinanceRouteChildren {
  AdminFinanceLedgerRoute: typeof AdminFinanceLedgerRoute
  AdminFinanceIndexRoute: typeof AdminFinanceIndexRoute
  AdminFinanceDisputeDisputeIdRoute: typeof AdminFinanceDisputeDisputeIdRoute
}

const AdminFinanceRouteChildren: AdminFinanceRouteChildren = {
  AdminFinanceLedgerRoute: AdminFinanceLedgerRoute,
  AdminFinanceIndexRoute: AdminFinanceIndexRoute,
  AdminFinanceDisputeDisputeIdRoute: AdminFinanceDisputeDisputeIdRoute,
}

const AdminFinanceRouteWithChildren = AdminFinanceRoute._addFileChildren(
  AdminFinanceRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminEditorialRoute: typeof AdminEditorialRoute
  AdminFinanceRoute: typeof AdminFinanceRouteWithChildren
  AdminHealthRoute: typeof AdminHealthRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTrustRoute: typeof AdminTrustRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminEditorialRoute: AdminEditorialRoute,
  AdminFinanceRoute: AdminFinanceRouteWithChildren,
  AdminHealthRoute: AdminHealthRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTrustRoute: AdminTrustRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCompleteRoute: typeof CheckoutCompleteRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCompleteRoute: CheckoutCompleteRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface StoreRouteChildren {
  StoreItemIdRoute: typeof StoreItemIdRoute
  StoreBeatsRoute: typeof StoreBeatsRoute
  StoreExclusivesRoute: typeof StoreExclusivesRoute
  StoreHifiRoute: typeof StoreHifiRoute
  StoreMerchRoute: typeof StoreMerchRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreItemIdRoute: StoreItemIdRoute,
  StoreBeatsRoute: StoreBeatsRoute,
  StoreExclusivesRoute: StoreExclusivesRoute,
  StoreHifiRoute: StoreHifiRoute,
  StoreMerchRoute: StoreMerchRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface StudioPodcastsRouteChildren {
  StudioPodcastsNewRoute: typeof StudioPodcastsNewRoute
  StudioPodcastsIndexRoute: typeof StudioPodcastsIndexRoute
}

const StudioPodcastsRouteChildren: StudioPodcastsRouteChildren = {
  StudioPodcastsNewRoute: StudioPodcastsNewRoute,
  StudioPodcastsIndexRoute: StudioPodcastsIndexRoute,
}

const StudioPodcastsRouteWithChildren = StudioPodcastsRoute._addFileChildren(
  StudioPodcastsRouteChildren,
)

interface StudioReleaseNewRouteChildren {
  StudioReleaseNewDetailsRoute: typeof StudioReleaseNewDetailsRoute
  StudioReleaseNewReviewRoute: typeof StudioReleaseNewReviewRoute
  StudioReleaseNewSplitsRoute: typeof StudioReleaseNewSplitsRoute
  StudioReleaseNewTracksRoute: typeof StudioReleaseNewTracksRoute
  StudioReleaseNewIndexRoute: typeof StudioReleaseNewIndexRoute
}

const StudioReleaseNewRouteChildren: StudioReleaseNewRouteChildren = {
  StudioReleaseNewDetailsRoute: StudioReleaseNewDetailsRoute,
  StudioReleaseNewReviewRoute: StudioReleaseNewReviewRoute,
  StudioReleaseNewSplitsRoute: StudioReleaseNewSplitsRoute,
  StudioReleaseNewTracksRoute: StudioReleaseNewTracksRoute,
  StudioReleaseNewIndexRoute: StudioReleaseNewIndexRoute,
}

const StudioReleaseNewRouteWithChildren =
  StudioReleaseNewRoute._addFileChildren(StudioReleaseNewRouteChildren)

interface StudioRouteChildren {
  StudioAnalyticsRoute: typeof StudioAnalyticsRoute
  StudioAudienceRoute: typeof StudioAudienceRoute
  StudioPayoutsRoute: typeof StudioPayoutsRoute
  StudioPodcastsRoute: typeof StudioPodcastsRouteWithChildren
  StudioProfileRoute: typeof StudioProfileRoute
  StudioReleasesRoute: typeof StudioReleasesRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioReleaseReleaseIdRoute: typeof StudioReleaseReleaseIdRoute
  StudioReleaseNewRoute: typeof StudioReleaseNewRouteWithChildren
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAnalyticsRoute: StudioAnalyticsRoute,
  StudioAudienceRoute: StudioAudienceRoute,
  StudioPayoutsRoute: StudioPayoutsRoute,
  StudioPodcastsRoute: StudioPodcastsRouteWithChildren,
  StudioProfileRoute: StudioProfileRoute,
  StudioReleasesRoute: StudioReleasesRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioReleaseReleaseIdRoute: StudioReleaseReleaseIdRoute,
  StudioReleaseNewRoute: StudioReleaseNewRouteWithChildren,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  EventsRoute: EventsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LyricsRoute: LyricsRoute,
  NotificationsRoute: NotificationsRoute,
  PodcastsRoute: PodcastsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StoreRoute: StoreRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  ArtistArtistIdRoute: ArtistArtistIdRoute,
  EventEventIdRoute: EventEventIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
  PodcastPodcastIdRoute: PodcastPodcastIdRoute,
  TrackTrackIdRoute: TrackTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
