package org.shakvilla.beatzmedia.identity.domain;

import java.time.Instant;

/**
 * Single-use, time-boxed password reset token. Identity ADD §3 / LLFR-IDENTITY-01.5.
 *
 * <p>Security: only the SHA-256 hash of the opaque random token is persisted ({@link
 * #tokenHash()}) — never the plaintext. The plaintext token is generated by the {@code
 * RequestPasswordResetService}, mailed to the user via the {@code Mailer} port, and discarded; it
 * is never stored or logged. {@link #used()} is flipped exactly once on redemption to enforce
 * single-use; {@link #isExpired(Instant)} enforces the time-box.
 */
public final class PasswordResetToken {

  private final String tokenHash;
  private final AccountId accountId;
  private final Instant expiresAt;
  private boolean used;

  public PasswordResetToken(String tokenHash, AccountId accountId, Instant expiresAt, boolean used) {
    this.tokenHash = tokenHash;
    this.accountId = accountId;
    this.expiresAt = expiresAt;
    this.used = used;
  }

  /** Factory for a freshly issued, unused token. */
  public static PasswordResetToken issue(String tokenHash, AccountId accountId, Instant expiresAt) {
    return new PasswordResetToken(tokenHash, accountId, expiresAt, false);
  }

  /** Returns true if {@code now} is at or after {@link #expiresAt()}. */
  public boolean isExpired(Instant now) {
    return !now.isBefore(expiresAt);
  }

  /** Marks this token as redeemed. Caller must have already checked {@link #used()}/expiry. */
  public void markUsed() {
    this.used = true;
  }

  public String tokenHash() {
    return tokenHash;
  }

  public AccountId accountId() {
    return accountId;
  }

  public Instant expiresAt() {
    return expiresAt;
  }

  public boolean used() {
    return used;
  }
}
